### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by mohammad-rahchamani** [CitizenHealth/COVIDx#1]
I can't find any documents on the roadmap of the project and the tasks. 
It would be nice to have a list of features so we can start working on the tasks.

**Comment by Murkantilism** [comment]
Entire PM is on Trello, here's the roadmap: https://trello.com/c/bG6tAfyu

**Comment by Murkantilism** [comment]
Update: while the overall roadmap will most likely remain in Trello, we're migrating individual tasks & features to Issues (here).

The roadmap might be loosely represented by Milestones, once I get around to creating more of them.
