### ISSUE TITLE
Implement all trivial questions for self-report form

### ISSUE THREAD

**Issue by Murkantilism** [CitizenHealth/COVIDx#11]
# Description
- Complete a basic implementation of most questions that are not-hard to implement
- **Note:** initial questionnaire is pending finalization, these are questions that I think will certainly be included
- **Note:** UI does **not** need to match storyboards/have high polish

# Acceptance Criteria
The following questions are implemented in the order listed:
- [ ] "How are you feeling?" is extended to support 5 options in vertical list format
  - Very Well
  - Well
  - Neutral
  - Unwell
  - Very Unwell
- [ ] Do you have any of these symptoms?
  - Dry cough
  - Wet cough (sputum)
  - Loss of taste
  - Loss of smell
  - Shortness of breath
  - Fatigue
  - Confusion
  - Abdominal pain
  - Chest pain
  - Diarrhea
  - Vomiting
  - Nausea
  - Sore Throat
  - Chills
  - Tightness in chest
  - Rash on feet
  - Headache
  - Other
    - Upon "Other" being clicked, it should become an editable text field (no input validation needed at this time, other than basic string sanitization)
- [ ] How old are you?
  - Under 18
  - 18-24
  - 25-40
  - 40-60
  - 60+
- [ ] What was your sex at birth?
  - Male
  - Female
  - Prefer not to say

**Comment by BrennenHodge** [comment]
I edited the last question. This is an important question in which XX or XY chromosomes make a big impact on mortality/morbidity with COVID-19. 

Re: age, for the purpose of details statistics, I think we should just have an open text field asking for their age or year of birth. E.g. "33 years" or "1986." 

[Asking the Age Question in Mail and Online Surveys](https://www.researchgate.net/publication/238103842_Asking_the_Age_Question_in_Mail_and_Online_Surveys) is research with stats on asking for age in surveys.

**Comment by lagph** [comment]
#16
