### ISSUE TITLE
Polish self-report form

### ISSUE THREAD

**Issue by Murkantilism** [CitizenHealth/COVIDx#14]
# Description
- Using art assets exported from Figma, pretty up the UI to match final storyboard as closely as possible
- Not ready to be picked up yet & blocked by issues #11, #12, & #13 

# Acceptance Criteria
- [ ] ToDo

**Comment by BrennenHodge** [comment]
@Murkantilism Since we will be heavily utilizing surveys for data collection, do you think we need to look more at a form builder that we can embed? 

I just came across https://tripetto.com/ and it looks awesome.

**Comment by Murkantilism** [comment]
> @Murkantilism Since we will be heavily utilizing surveys for data collection, do you think we need to look more at a form builder that we can embed?

A prudent question @BrennenHodge. My chief concern with an embedded form is the disconnect that could create with the gamification features. A secondary concern is that an embedded form could make it a little _more_ complicated to implement the "contact-nurturing" ideas discussed during the all-hands mtg, like having new and/or dynamic questions shown to users each time they took the survey.

There are certainly benefits though, by leveraging a third-party solution for forms and embedding them, we can entirely skip a bunch of frontend work and re-focus that effort to other features like the Map or Dashboard. We should make a pros/cons list and discuss it further.

**Comment by Murkantilism** [comment]
P.S. - I like [responster](https://www.responster.com/) personally

**Comment by BrennenHodge** [comment]
@Murkantilism My criteria while searching for a form builder was 1) free and 2) open source with a permissive license (MIT preferred). 

Reasons why I like [Tripetto](https://tripetto.com/):

1. Conversational flow (like Typeform)
2. Advanced logic 
3. Visual editor (and thus the speed of refinements)

1 and 2 can be achieved with our current setup. Not so much with #3. 

I'm also thinking about the UX. Using a form SDK such as Tripetto would give us a nice UX right out of the box. We'll have to design that with our current setup. 

My main concerns are the same concerns you mentioned. 

@ohitsdoh also has concerns over app bloat & performance. 

The best way to answer these questions is to spend some time implementing Tripetto to test our concerns. Maybe we can get a volunteer who is standing by to test this out.

**Comment by Murkantilism** [comment]
@BrennenHodge yeah responster is closed source, unfortunately, but for our needs it'd be free.

I started a pro's & con's list of using _any_ third party form on Trello [here](https://trello.com/c/me0oOjCl/118-3rd-party-forms-or-no), please add your thoughts.

The reason I picked Trello instead of a list in here that we can both edit is just in case any other folks have thoughts they can contribute but aren't watching GitHub or don't have repo access.

**Comment by BrennenHodge** [comment]
@Murkantilism This is an example of Tripetto's WordPress plugin I put together in 30 minutes: https://citizenhealth.io/form-test/

I think this checks all the boxes you added on Trello. The easiest way to decide is for someone to spend one hour installing the [Tripetto SDK](https://tripetto.com/sdk/developers/) in our app just to test it out. 

@ahmadhuzaifa @ohitsdoh @Mariefay Anyone want to take this task on?

**Comment by Murkantilism** [comment]
Closing out now that we've adopted Tripetto.
