### ISSUE TITLE
"Checking in" loads a blank modal

### ISSUE THREAD

**Issue by BrennenHodge** [CitizenHealth/COVIDx#26]
@afixoftrix 

![image](https://user-images.githubusercontent.com/3343429/83312518-30165800-a1d8-11ea-8fe1-51e01399a494.png)

**Comment by BrennenHodge** [comment]
This modal needs to take up the whole view on desktop and mobile like the design below:

![Frame 2](https://user-images.githubusercontent.com/3343429/83312588-779ce400-a1d8-11ea-81d0-35b8a7d3bb78.png)

And like the actual Tripetto survey: https://tripetto.app/collect/LJ9GM8MW3X

The reason is we want the user's full attention on completing the survey, not wondering what the stuff is behind it.

**Comment by Murkantilism** [comment]
@BrennenHodge can you elaborate on "like the actual Trepetto"? I thought the plan was to embed Tripetto right into the site?

**Comment by Murkantilism** [comment]
Also based on what @afixoftrix wrote in the PR for the token fix, I think this issue might be for me instead:

>We need to make sure the .env file on the server hosting the app has the correct variable and value.

When I did the last deploy I definitely didn't create a .env file so one may not be present on the server (or is present without the right variables).

**Comment by Murkantilism** [comment]
@BrennenHodge @afixoftrix yep I just ran another deploy after creating a .env file with [this value](https://github.com/CitizenHealth/COVIDx/pull/22/files#diff-f579cccc964135c7d644c7b2d3b0d3ecL1), form is no longer blank (it's the Tripetto).

**Comment by Murkantilism** [comment]
Oh sry, forgot about the fullscreen part of this ticket, will re-open so we can tackle that.

**Comment by BrennenHodge** [comment]
> @BrennenHodge can you elaborate on "like the actual Trepetto"? I thought the plan was to embed Tripetto right into the site?

The [link](https://tripetto.app/collect/LJ9GM8MW3X) I referenced is full screen and has the form centered. 

The "large" modal size mentioned in #28 will work, but the form needs to be centered horizontally.
